name = "iva8m1gora"
author = "flamelynx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "813efec29e53099cca670bb9ad4fc972c32d57a606e58d638da7301e6a5d04bd"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
