name = "iva8m1gora"
author = "flamelynx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5661fea8cafbfb3f9bdccad364ceaf77022670296a19095ccb5fbf44f5e84189"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
