name = "iva8m1gora"
author = "flamelynx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67c0f9c79df5a3fabb8e6079d2877d07681beb2db01814ff2f09fe80760d2f01"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
